### PR TITLE
Club List and Profile Page User Interface and Integration

### PR DESCRIPTION
**Pull request by mdhishaamakhtar**
# Pull Request Type
Please check the type of change your PR introduces:
- Feature

# Purpose
- To implement the user interface of clubs list and user profile as in the [design](https://www.figma.com/file/Dv33wVcrx1xeYx8NwdUUe8/KEATS)

# Approach
- Using material components to style

#### Issue Reference: #7 and #9

# Did you learn something new?
- Styling in Android

### CODE REVIEW

**Comment by mdhishaamakhtar** [comment]
@SphericalKat @BRO3886 I'm also doing things apart from just the UI so I'm mentioning other issues here as well

**Comment by mdhishaamakhtar** [comment]
Working with another issue as well: #9

**Comment by mdhishaamakhtar** [comment]
@SaurusXI  @BRO3886 The actions are just queued indefinitely for some reason please check

**Comment by SaurusXI** [comment]
Startup failure. Maybe it's related to the GitHub outage

**Pull request merged**
