### PR TITLE
User Profile and Club Members List and Join Club Implementation

### PR DESCRIPTION
**Pull request by mdhishaamakhtar**
- Rest of the user interface specifically user profile and club members list and join club using material components

#### Issue Reference: #7

### CODE REVIEW

**Comment by BRO3886** [comment]
@mdhishaamakhtar can you delete the PR template?

**Comment by mdhishaamakhtar** [comment]
> @mdhishaamakhtar can you delete the PR template?

Done

**Comment by mdhishaamakhtar** [comment]
@BRO3886 can you merge this?

**Comment by mdhishaamakhtar** [comment]
@SphericalKat

**Pull request merged**
